<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4kBYx0N\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4kBYx0N/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4kBYx0N.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4kBYx0N\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4kBYx0N\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4kBYx0N',
    'container.build_id' => 'd3f2ee93',
    'container.build_time' => 1630221160,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4kBYx0N');
